# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [3]:
import numpy as np 




### 2. Print the NUMPY version and the configuration.


In [4]:
#print installed version of NumPy
print("NumPy Version:", np.__version__) 

NumPy Version: 2.1.3


In [5]:
#prints configuration of my NumPy version. 
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/naatt/anaconda3/Library/include
    lib directory: C:/Users/naatt/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/naatt/anaconda3/Library/include
    lib directory: C:/Users/naatt/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cython
    name: cython
  

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
a = np.random.random([2,3,5])



### 4. Print a.


In [7]:
a

array([[[0.08607347, 0.55862378, 0.32025883, 0.09586768, 0.55008824],
        [0.76673549, 0.32945111, 0.94517036, 0.03495318, 0.04840134],
        [0.0467557 , 0.56499578, 0.00262112, 0.89694342, 0.5194399 ]],

       [[0.61089886, 0.49238972, 0.97898067, 0.83519242, 0.16529709],
        [0.93281383, 0.2197997 , 0.86802425, 0.32937311, 0.55823196],
        [0.7967864 , 0.49814126, 0.15026015, 0.68791184, 0.478662  ]]])

In [8]:
a.shape

(2, 3, 5)

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [9]:
b = np.ones([5,2,3])



### 6. Print b.


In [10]:
b


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [11]:
if a.size == b.size:
    print ("a and b have the same size")
else:
    print("a and b are not the same size")


a and b have the same size


In [12]:
ab = (a.size == b.size)
ab

True


### 8. Are you able to add a and b? Why or why not?


In [13]:
np.add (a, b)
# it's not possible as the shape of the matrix is not the same. 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [15]:
print(a.shape)
print(b.shape)


(2, 3, 5)
(5, 2, 3)


In [16]:
transpose_b = np.transpose(b)
print(transpose_b)
print(transpose_b.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(3, 2, 5)


In [17]:
c = np.reshape(transpose_b, (2,3,5))
print(c)
print(c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [18]:
d = a + c
print("Sum of Values: ",d)


Sum of Values:  [[[1.08607347 1.55862378 1.32025883 1.09586768 1.55008824]
  [1.76673549 1.32945111 1.94517036 1.03495318 1.04840134]
  [1.0467557  1.56499578 1.00262112 1.89694342 1.5194399 ]]

 [[1.61089886 1.49238972 1.97898067 1.83519242 1.16529709]
  [1.93281383 1.2197997  1.86802425 1.32937311 1.55823196]
  [1.7967864  1.49814126 1.15026015 1.68791184 1.478662  ]]]


In [19]:
d = np.add (a,c)
print("Sum of Values: ",d)

Sum of Values:  [[[1.08607347 1.55862378 1.32025883 1.09586768 1.55008824]
  [1.76673549 1.32945111 1.94517036 1.03495318 1.04840134]
  [1.0467557  1.56499578 1.00262112 1.89694342 1.5194399 ]]

 [[1.61089886 1.49238972 1.97898067 1.83519242 1.16529709]
  [1.93281383 1.2197997  1.86802425 1.32937311 1.55823196]
  [1.7967864  1.49814126 1.15026015 1.68791184 1.478662  ]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [20]:
print(f"A = {a}")

print(f"\nD = {d}")

#Array D is array A with each element increased by 1. 

A = [[[0.08607347 0.55862378 0.32025883 0.09586768 0.55008824]
  [0.76673549 0.32945111 0.94517036 0.03495318 0.04840134]
  [0.0467557  0.56499578 0.00262112 0.89694342 0.5194399 ]]

 [[0.61089886 0.49238972 0.97898067 0.83519242 0.16529709]
  [0.93281383 0.2197997  0.86802425 0.32937311 0.55823196]
  [0.7967864  0.49814126 0.15026015 0.68791184 0.478662  ]]]

D = [[[1.08607347 1.55862378 1.32025883 1.09586768 1.55008824]
  [1.76673549 1.32945111 1.94517036 1.03495318 1.04840134]
  [1.0467557  1.56499578 1.00262112 1.89694342 1.5194399 ]]

 [[1.61089886 1.49238972 1.97898067 1.83519242 1.16529709]
  [1.93281383 1.2197997  1.86802425 1.32937311 1.55823196]
  [1.7967864  1.49814126 1.15026015 1.68791184 1.478662  ]]]



### 12. Multiply a and c. Assign the result to e.


In [21]:
e = np.multiply (a,c)
print("\n Multiplication of Values: ",e)


 Multiplication of Values:  [[[0.08607347 0.55862378 0.32025883 0.09586768 0.55008824]
  [0.76673549 0.32945111 0.94517036 0.03495318 0.04840134]
  [0.0467557  0.56499578 0.00262112 0.89694342 0.5194399 ]]

 [[0.61089886 0.49238972 0.97898067 0.83519242 0.16529709]
  [0.93281383 0.2197997  0.86802425 0.32937311 0.55823196]
  [0.7967864  0.49814126 0.15026015 0.68791184 0.478662  ]]]




### 13. Does e equal to a? Why or why not?


In [22]:
e == a
#e and a are equal because they both got multiplied by 1 hence why the answers remain the same. 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [23]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9789806653581417
1.002621121276285
1.4789714220514334



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [24]:
f = np.empty ([2,3,5])





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [25]:
print(d)

[[[1.08607347 1.55862378 1.32025883 1.09586768 1.55008824]
  [1.76673549 1.32945111 1.94517036 1.03495318 1.04840134]
  [1.0467557  1.56499578 1.00262112 1.89694342 1.5194399 ]]

 [[1.61089886 1.49238972 1.97898067 1.83519242 1.16529709]
  [1.93281383 1.2197997  1.86802425 1.32937311 1.55823196]
  [1.7967864  1.49814126 1.15026015 1.68791184 1.478662  ]]]


In [26]:
# Loop over the first dimension (layers) of the 3D array d
for i in range(d.shape[0]):
    # Loop over the second dimension (rows) of each layer in d
    for j in range(d.shape[1]):
        # Loop over the third dimension (columns) of each row in each layer
        for k in range(d.shape[2]):
            # Get the current value to avoid repeated indexing
            current_value = d[i, j, k]
            # If the current element is equal to the minimum value in d
            if current_value == d_min:
                f[i, j, k] = 0  # Assign 0 to the corresponding position in f
            # If the current element is equal to the maximum value in d
            elif current_value == d_max:
                f[i, j, k] = 100  # Assign 100 to the corresponding position in f
            # If the current element is equal to the mean value in d
            elif current_value == d_mean:
                f[i, j, k] = 50  # Assign 50 to the corresponding position in f
            # If the current element is greater than the minimum but less than the mean
            elif d_min < current_value < d_mean:
                f[i, j, k] = 25  # Assign 25 to the corresponding position in f
            # If the current element is greater than the mean but less than the maximum
            elif d_mean < current_value < d_max:
                f[i, j, k] = 75  # Assign 75 to the corresponding position in f

In [27]:
print (f)

[[[ 25.  75.  25.  25.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  75.   0.  75.  75.]]

 [[ 75.  75. 100.  75.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  75.  25.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [28]:
print(f"D = {d}")

print(f"\nF = {f}")


D = [[[1.08607347 1.55862378 1.32025883 1.09586768 1.55008824]
  [1.76673549 1.32945111 1.94517036 1.03495318 1.04840134]
  [1.0467557  1.56499578 1.00262112 1.89694342 1.5194399 ]]

 [[1.61089886 1.49238972 1.97898067 1.83519242 1.16529709]
  [1.93281383 1.2197997  1.86802425 1.32937311 1.55823196]
  [1.7967864  1.49814126 1.15026015 1.68791184 1.478662  ]]]

F = [[[ 25.  75.  25.  25.  75.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  75.   0.  75.  75.]]

 [[ 75.  75. 100.  75.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  75.  25.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [29]:
f = np.empty(d.shape, dtype=str)  # Create an array with the same shape as d, specifying the dtype as str

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            current_value = d[i, j, k]
            
            if current_value == d_min:
                f[i, j, k] = 'A'  # Assign 'A' for d_min
            elif current_value == d_max:
                f[i, j, k] = 'B'  # Assign 'B' for d_max
            elif current_value > d_mean:
                f[i, j, k] = 'C'  # Assign 'C' for values greater than d_mean
            elif current_value == d_mean:
                f[i, j, k] = 'D'  # Assign 'D' for values equal to d_mean
            else:  # Covers the case where current_value < d_mean
                f[i, j, k] = 'E'  # Assign 'E' for values less than d_mean

print (f)

[[['E' 'C' 'E' 'E' 'C']
  ['C' 'E' 'C' 'E' 'E']
  ['E' 'C' 'A' 'C' 'C']]

 [['C' 'C' 'B' 'C' 'E']
  ['C' 'E' 'C' 'E' 'C']
  ['C' 'C' 'E' 'C' 'E']]]
